### ISSUE TITLE
smartie-sv-dependency issue

### ISSUE THREAD

**Issue by awaisfarooq724** [caixu0518/ITIPs#1]
Hi
I am trying to install smartie-sv in the server but it is causing many errors as follows.

(base) baicai@18:08:35 /home/data1/baicai/AWAIS$ cd smartie-sv-master && make
cd src/blasr && make && cp alignment/bin/blasr ../../bin/blasr && cp alignment/bin/sawriter ../../bin/sawriter
make[1]: Entering directory '/home/data1/baicai/AWAIS/smartie-sv-master/src/blasr'
make[1]: *** No targets specified and no makefile found. Stop.
make[1]: Leaving directory '/home/data1/baicai/AWAIS/smartie-sv-master/src/blasr'
make: *** [Makefile:6: bin/blasr] Error 2

is there anyway around to install it or circumvent this error to install ITIPs on my server?
Please help, looking forward to your response.

**Comment by caixu0518** [comment]
Sorry,  I dont know why it happens. I didn't encounter this problem. 

maybe you can get  solutions from the smartie-sv team (https://github.com/zeeev/smartie-sv)

Best,
Xu Cai

**Comment by awaisfarooq724** [comment]
thanks for the information
