### ISSUE TITLE
How to detect the aligned and unaligned regions in step 2 ?

### ISSUE THREAD

**Issue by Bobo22331** [caixu0518/ITIPs#2]
Hi, 

In Step 2, is there any scripts to detect the aligned and unaligned regions ?

**Comment by caixu0518** [comment]
Sorry, i didnt include scripts in this step. here is my idea to do this.

The concepts were based on Chiifu-401 genomic sequences (reference genome). If genomic sequences from the other 19 accessions could be covered by the Chiifu-401 sequences, we denoted such regions as being ‘aligned regions’; if the genomic sequences in the other genomes could not be covered by the Chiifu-401 sequences, we defined them as ‘unaligned regions’. 

Best.
Xu

**Comment by Bobo22331** [comment]
@caixu0518 Thank you! And is there any other tools to do that ? smartie-sv or minimap2 is OK?

**Comment by caixu0518** [comment]
I used smartie-sv.

**Comment by Bobo22331** [comment]
OK! Thank you!
